### ISSUE TITLE
Modification of `persistance` to `persistence` in Callback Configuration Should Be Handled

### ISSUE THREAD

**Issue by tres** [pixelunion/elixir-shopifyapi#367]
Hey!

Hope you all are well. Thanks again for this library. I really like it not just for its utility, but also the great architectural decisions and the excellent implementation and best practices. Thanks!

So it looks like when things were moved from Genserver to ETS in AuthTokenServer, ShopServer and AppServer, the mechanism used for looking up configuration callbacks got changed as well. This is all very nice; however, the callback key seems to have been changed from `persistance` to `persistence.`

https://github.com/pixelunion/elixir-shopifyapi/blob/31717220a23098835825b9663655055fa40b028c/lib/shopify_api/auth_token_server.ex#L86

vs

https://github.com/pixelunion/elixir-shopifyapi/blob/9c788d55b1e65413687f65632099dd700f1f6f49/lib/shopify_api/auth_token_server.ex#L56

Having two different spellings of persistence seems like it's probably going to be an ongoing issue & so this change seems to make good sense. It would just be nice to have that change denoted in the changelog as a breaking change as well as getting the readme updated to denote the new callback key.

Thanks again!

Tres

**Comment by tres** [comment]
(writing as a ticket since I'm not sure how you'd prefer to deal with this)

**Comment by hez** [comment]
@tres good find, looks like there was a spelling mistake originally.  We should have made a `BREAKING` changelog entry when we change this! Sorry about that!
