### ISSUE TITLE
App name hardcoded unintentionally in AdminAuthenticator?

### ISSUE THREAD

**Issue by dylanfareed** [pixelunion/elixir-shopifyapi#455]
It looks like an an app named `up_sell` has been hardcoded here in the `ShopifyAPI.Plugs.AdminAuthenticator` plug.

Is that intentional?
https://github.com/orbit-apps/elixir-shopifyapi/blob/1c96862bec976719e086f5e9de0ec84edc23e245/lib/shopify_api/plugs/admin_authenticator.ex#L90

**Comment by hez** [comment]
@dylanfareed good find, not that shouldn't be hard coded!
